#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="${1:-$ROOT_DIR/Code.single.gs}"
SRC_FILE="$ROOT_DIR/Code.gs"

{
  echo "// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY."
  echo "// Generated by scripts/build_single_gas.sh on $(date '+%Y-%m-%d %H:%M:%S')"
  echo "// SOURCE: Code.gs"
  echo ""
  if [[ ! -f "$SRC_FILE" ]]; then
    echo "// ERROR: missing file Code.gs" >&2
    exit 1
  fi
  cat "$SRC_FILE"
} > "$OUT_FILE"

echo "Built: $OUT_FILE"
