#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="${1:-$ROOT_DIR/Code.single.gs}"

FILES=(
  "01_config.gs"
  "02_entry_points.gs"
  "03_request_parsing_and_bot_health.gs"
  "04_sheet_storage.gs"
  "05_orders_create_update.gs"
  "06_telegram_publish_group.gs"
  "07_telegram_updates_callbacks.gs"
  "08_commands_messages_status_flow.gs"
  "09_telegram_text_photo_reminders.gs"
  "10_notifications_and_datetime.gs"
  "11_webhook_city_misc.gs"
  "12_diagnostics_and_setup.gs"
  "13_telegram_bot_commands.gs"
)

{
  echo "// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY."
  echo "// Generated by scripts/build_single_gas.sh on $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""
  for f in "${FILES[@]}"; do
    if [[ ! -f "$ROOT_DIR/$f" ]]; then
      echo "// ERROR: missing file $f" >&2
      exit 1
    fi
    echo ""
    echo "// =============================="
    echo "// SOURCE: $f"
    echo "// =============================="
    cat "$ROOT_DIR/$f"
    echo ""
  done
} > "$OUT_FILE"

echo "Built: $OUT_FILE"
